# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Tox OOP API IR
repo_url: https://github.com/roihershberg/tox-oop-api-ir
repo_name: roihershberg/tox-oop-api-ir

nav:
  - 'Home': 'index.md'
  - 'Reference':
      - 'reference/index.md'
      - 'IREnum': 'reference/enum.md'
      - 'IREnumValue': 'reference/enum_value.md'
      - 'IRException': 'reference/exception.md'
      - 'IRClass': 'reference/class.md'
      - 'IRNativeHandle': 'reference/native_handle.md'
      - 'IRNumberHandle': 'reference/number_handle.md'
      - 'IRProperty': 'reference/property.md'
      - 'IRFunction': 'reference/function.md'
      - 'IRReturnType': 'reference/return_type.md'
      - 'IRBufferWrapper': 'reference/buffer_wrapper.md'
      - 'IRParam': 'reference/param.md'
      - 'IRType': 'reference/type.md'
      - 'CType': 'reference/ctype.md'

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.indexes
    - navigation.top
    - search
    - search.suggest
    - search.highlight

extra_css:
  - stylesheets/extra.css

extra:
  version:
    provider: mike

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - def_list

plugins:
  - reflinkfixer
  - minify:
        minify_html: true
        minify_js: true
        minify_css: true
        htmlmin_opts:
          remove_comments: true
        css_files:
          - stylesheets/extra.css
